user www-data;
worker_processes 1;
pid /run/nginx.pid;
events { worker_connections 128; }
http {
  include /etc/nginx/mime.types;
  access_log /dev/stdout;
  error_log /dev/stderr;
  server {
    listen 172.30.32.1:8100;
    allow 172.30.32.2;
    deny all;
    location / {
      proxy_pass http://172.30.32.1:631;
      proxy_bind 172.30.32.1;
      proxy_set_header Host localhost;
      proxy_set_header Accept-Encoding "";
      proxy_set_header Authorization $http_authorization;
      proxy_set_header X-Ingress-Path $http_x_ingress_path;
      proxy_redirect ~^https?://[^/]+(/.*)$ $http_x_ingress_path$1;
      proxy_redirect ~^(/.*)$ $http_x_ingress_path$1;
      sub_filter_once off;
      sub_filter 'href="/' 'href="$http_x_ingress_path/';
      sub_filter 'action="/' 'action="$http_x_ingress_path/';
      sub_filter 'src="/' 'src="$http_x_ingress_path/';
    }
  }
}
