name: SANE L3210 Scanner
version: "0.8.2"
slug: sane_l3210
description: Network scanner sharing for the Epson L3210 over SANE
image: ghcr.io/duyleekun/homeassistant-epson-sane_l3210
arch:
  - amd64
usb: true
homeassistant_api: true
init: false
startup: services
boot: auto
host_network: true
stage: stable
ports:
  6566/tcp: 6566
ports_description:
  6566/tcp: SANE network scanner service
map:
  - share:rw
